# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/MiniZed_Constraints_Rev1_170613.xdc

# Block Designs: bd/PLtoPSInterrupt/PLtoPSInterrupt.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt || ORIG_REF_NAME==PLtoPSInterrupt} -quiet] -quiet

# IP: bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_processing_system7_0_0/PLtoPSInterrupt_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt_processing_system7_0_0 || ORIG_REF_NAME==PLtoPSInterrupt_processing_system7_0_0} -quiet] -quiet

# IP: bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt_axi_gpio_0_0 || ORIG_REF_NAME==PLtoPSInterrupt_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_ps7_0_axi_periph_0/PLtoPSInterrupt_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt_ps7_0_axi_periph_0 || ORIG_REF_NAME==PLtoPSInterrupt_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_rst_ps7_0_50M_0/PLtoPSInterrupt_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt_rst_ps7_0_50M_0 || ORIG_REF_NAME==PLtoPSInterrupt_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_xbar_0/PLtoPSInterrupt_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt_xbar_0 || ORIG_REF_NAME==PLtoPSInterrupt_xbar_0} -quiet] -quiet

# IP: bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_PLtoPSinterrupt_0_0/PLtoPSInterrupt_PLtoPSinterrupt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt_PLtoPSinterrupt_0_0 || ORIG_REF_NAME==PLtoPSInterrupt_PLtoPSinterrupt_0_0} -quiet] -quiet

# IP: bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_auto_pc_0/PLtoPSInterrupt_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PLtoPSInterrupt_auto_pc_0 || ORIG_REF_NAME==PLtoPSInterrupt_auto_pc_0} -quiet] -quiet

# XDC: bd/PLtoPSInterrupt/PLtoPSInterrupt_ooc.xdc
