# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_xbar_0/PLtoPSInterrupt_xbar_0.xci
# IP: The module: 'PLtoPSInterrupt_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_xbar_0/PLtoPSInterrupt_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_xbar_0/PLtoPSInterrupt_xbar_0.xci
# IP: The module: 'PLtoPSInterrupt_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_xbar_0/PLtoPSInterrupt_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
