# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0.xci
# IP: The module: 'PLtoPSInterrupt_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0.xci
# IP: The module: 'PLtoPSInterrupt_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PLtoPS_demo_3.1/PLtoPS_demo_3.1.srcs/sources_1/bd/PLtoPSInterrupt/ip/PLtoPSInterrupt_axi_gpio_0_0/PLtoPSInterrupt_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLtoPSInterrupt_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
