# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/39389/Desktop/Vivado_Workspace/Minized_Espulsore_v_1/Minized_Espulsore_v_1.srcs/sources_1/bd/design_1/ip/design_1_axi_espulsore_0_1/design_1_axi_espulsore_0_1.xci
# IP: The module: 'design_1_axi_espulsore_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/Minized_Espulsore_v_1/Minized_Espulsore_v_1.srcs/sources_1/bd/design_1/ip/design_1_axi_espulsore_0_1/MiniZed_Constraints_Rev1_170613.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_espulsore_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/39389/Desktop/Vivado_Workspace/Minized_Espulsore_v_1/Minized_Espulsore_v_1.srcs/sources_1/bd/design_1/ip/design_1_axi_espulsore_0_1/design_1_axi_espulsore_0_1.xci
# IP: The module: 'design_1_axi_espulsore_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/Minized_Espulsore_v_1/Minized_Espulsore_v_1.srcs/sources_1/bd/design_1/ip/design_1_axi_espulsore_0_1/MiniZed_Constraints_Rev1_170613.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_espulsore_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
