# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xci
# IP: The module: 'design_1_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xci
# IP: The module: 'design_1_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/39389/Desktop/Vivado_Workspace/PS_PL_codesign_demo_1/PS_PL_codesign_demo_1.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_4/design_1_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
